version: "2"

services:
  app:
    container_name: "app"
    image: "ng4381/wildfly-app"
    environment:
      - WILDFLY_USER=admin
      - WILDFLY_PASS=adminPassword
      - DB_NAME=zkossdb
      - DB_USER=root
      - DB_PASS=123qweASD
      - DB_URI=db:3306
    depends_on:
      - zkossdb
    ports:
      - "8080:8080" # application
      - "9990:9990" # admin console

  zkossdb:
    container_name: "zkossdb"
    image: "mysql:latest"
    environment:
      - MYSQL_DATABASE=zkossdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123qweASD
      - MYSQL_ROOT_PASSWORD=123qweASD
    volumes:
      - ./workdir/db/init/:/docker-entrypoint-initdb.d/ # init database
      - ./workdir/db/data/:/var/lib/mysql/              # data storage
    ports:
      - "3306:3306"
#  liquibase:
#    # Image to be pulled from Docker Hub
#    image: liquibase/liquibase:4.9.1
#    # Name of the container
#    container_name: Liquibase_container
#    # Setting depends_on to PostgreSQL container to wait till the service is ready to accept connections
#    depends_on:
#      zkossdb:
#        condition: service_healthy
#    # Volume to add the liquibase collection of scripts
#    volumes:
#      - ./src/main/resources/db/changelog/:/liquibase/changelog/
#    # Command to run the liquibase update service
#    command: --defaults-file=/liquibase/changelog/liquibase.properties update
networks:
  default:
    driver: bridge