version: "3.9"
services:
  app:
    build: .
    environment:
      - WILDFLY_USER=admin
      - WILDFLY_PASS=adminPassword
      - DB_NAME=zkossdb
      - DB_USER=admin
      - DB_PASS=password
      - DB_URI=db:3306
    depends_on:
      - db
    ports:
      - "8082:8080" # application
      - "9990:9990" # admin console
  db:
    image: mysql:8.0.32
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: zkossdb
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10
    volumes:
      # - "test_db2:/var/lib/mysql"
      - zkossdb_init:/docker-entrypoint-initdb.d/ # init database
      - zkossdb_data:/var/lib/mysql/              # data storage

  # for php myadmin goto http://localhost:8080
  db_admin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    restart: "on-failure"
    depends_on:
      - db
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: password
  liquibase:
    image: liquibase/liquibase:latest
    container_name: Liquibase_container
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src/resources/db/changelog/:/liquibase/changelog/
    command: liquibase --defaults-file=/liquibase/changelog/liquibase.properties --classpath=/liquibase/changelog/mysql-connector-j-8.0.32.jar --searchPath=/liquibase/changelog update

volumes:
  zkossdb_init:
  zkossdb_data: